import type { Collection } from "tinacms";
import { enabledField, eyebrowField, linkField, paragraphsField, seoField, textarea } from "./fields";

export const homeCollection: Collection = {
  name: "home",
  label: "Home",
  path: "src/content/home",
  format: "json",
  ui: { allowedActions: { create: false, delete: false } },
  fields: [
    {
      type: "object",
      name: "hero",
      label: "Hero",
      fields: [
        enabledField,
        { name: "autoplay", label: "Avanzar solo cada 6,5 s", type: "boolean" },
        {
          type: "object",
          name: "slides",
          label: "Slides",
          list: true,
          ui: { itemProps: (item) => ({ label: item?.title?.replace(/\n/g, " ") || "Slide" }) },
          fields: [
            { name: "image", label: "Imagen", type: "image" },
            { name: "imageAlt", label: "Texto alternativo", type: "string" },
            {
              name: "imageMobile",
              label: "Imagen en móvil",
              description: "Opcional. Vertical, p. ej. 780×1700. Sin ella se usa la imagen principal, centrada.",
              type: "image",
            },
            {
              name: "focus",
              label: "Encuadre en escritorio",
              description: "Posición del foco de la imagen, p. ej. 50% 50%.",
              type: "string",
            },
            { name: "title", label: "Título", description: "Admite saltos de línea.", type: "string", ui: textarea },
            { name: "text", label: "Texto", type: "string", ui: textarea },
            linkField("cta", "Botón"),
            {
              name: "scrim",
              label: "Oscurecer imagen (%)",
              description: "De 0 a 40. Úsalo si el texto no se lee sobre la foto.",
              type: "number",
            },
          ],
        },
      ],
    },
    {
      type: "object",
      name: "marquee",
      label: "Banda de mensajes",
      fields: [
        enabledField,
        {
          type: "object",
          name: "items",
          label: "Mensajes",
          list: true,
          ui: { itemProps: (item) => ({ label: item?.label || "Mensaje" }) },
          fields: [{ name: "label", label: "Texto", type: "string" }],
        },
      ],
    },
    {
      type: "object",
      name: "products",
      label: "Productos destacados",
      description: "Muestra hasta 4 productos marcados como destacados en WooCommerce.",
      fields: [
        enabledField,
        eyebrowField,
        { name: "title", label: "Título", type: "string", ui: textarea },
        linkField("cta", "Botón"),
      ],
    },
    {
      type: "object",
      name: "services",
      label: "Servicios",
      fields: [
        enabledField,
        eyebrowField,
        { name: "title", label: "Título", description: "Admite saltos de línea.", type: "string", ui: textarea },
        { name: "description", label: "Descripción", type: "string", ui: textarea },
        { name: "ctaLabel", label: "Texto del enlace de cada tarjeta", type: "string" },
        {
          type: "object",
          name: "items",
          label: "Servicios",
          list: true,
          ui: { itemProps: (item) => ({ label: item?.title || "Servicio" }) },
          fields: [
            { name: "image", label: "Imagen (16:10)", type: "image" },
            { name: "title", label: "Título", type: "string" },
            { name: "text", label: "Texto", type: "string", ui: textarea },
            { name: "url", label: "URL", type: "string" },
          ],
        },
      ],
    },
    {
      type: "object",
      name: "essence",
      label: "Nuestra esencia",
      fields: [
        enabledField,
        eyebrowField,
        { name: "title", label: "Título", description: "Admite saltos de línea.", type: "string", ui: textarea },
        paragraphsField,
        linkField("cta", "Enlace"),
      ],
    },
    {
      type: "object",
      name: "results",
      label: "Resultados",
      fields: [
        enabledField,
        eyebrowField,
        { name: "title", label: "Título", type: "string", ui: textarea },
        paragraphsField,
        {
          type: "object",
          name: "stats",
          label: "Cifras",
          list: true,
          ui: { itemProps: (item) => ({ label: item?.label || "Cifra" }) },
          fields: [
            { name: "value", label: "Valor", type: "number" },
            { name: "prefix", label: "Prefijo", description: "p. ej. +", type: "string" },
            { name: "suffix", label: "Sufijo", description: "p. ej. %", type: "string" },
            { name: "label", label: "Etiqueta", type: "string" },
          ],
        },
        { name: "beforeImage", label: "Imagen de antes", type: "image" },
        { name: "afterImage", label: "Imagen de después", type: "image" },
        { name: "beforeLabel", label: "Etiqueta de antes", type: "string" },
        { name: "afterLabel", label: "Etiqueta de después", type: "string" },
      ],
    },
    {
      type: "object",
      name: "journal",
      label: "Skin Journal",
      description: "Muestra el post destacado más reciente y los 2 últimos del blog.",
      fields: [
        enabledField,
        eyebrowField,
        { name: "title", label: "Título", type: "string" },
        { name: "ctaLabel", label: "Texto del enlace", type: "string" },
        { name: "ctaLabelMobile", label: "Texto del enlace en móvil", type: "string" },
        { name: "ctaUrl", label: "URL del enlace", type: "string" },
      ],
    },
    {
      type: "object",
      name: "pillars",
      label: "Nuestra forma",
      fields: [
        enabledField,
        { name: "title", label: "Título", type: "string" },
        {
          type: "object",
          name: "items",
          label: "Pilares",
          list: true,
          ui: { itemProps: (item) => ({ label: item?.title || "Pilar" }) },
          fields: [
            { name: "title", label: "Título", type: "string" },
            { name: "text", label: "Texto", type: "string", ui: textarea },
          ],
        },
      ],
    },
    {
      type: "object",
      name: "booking",
      label: "Reserva",
      description: "El botón usa la URL de WhatsApp de las redes del footer.",
      fields: [
        enabledField,
        eyebrowField,
        {
          name: "title",
          label: "Título",
          description: "Admite saltos de línea. Lo que va entre *asteriscos* se muestra en itálica.",
          type: "string",
          ui: textarea,
        },
        { name: "text", label: "Texto", type: "string", ui: textarea },
        { name: "ctaLabel", label: "Texto del botón", type: "string" },
      ],
    },
    seoField("SEO de la home"),
  ],
};
